#! /bin/bash
clear
_homeCompDate="198910030927"
read -a _count
echo count= $_count


renamelogs()
{

echo renamelogs
    if [ -f "mylog_6.log" ];then
        rm -rf mylog_6.log
    fi
    if [ -f "mylog_5.log" ];then
        mv mylog_5.log mylog_6.log
    fi
    if [ -f "mylog_4.log" ];then
            mv mylog_4.log mylog_5.log
    fi
    if [ -f "mylog_3.log" ];then
        mv mylog_3.log mylog_4.log
    fi
    if [ -f "mylog_2.log" ];then
        mv mylog_2.log mylog_3.log
    fi
    if [ -f "mylog_1.log" ];then
        echo mv mylog_1.log mylog_2.log
        mv mylog_1.log mylog_2.log
    fi

}

log()
{
logline=$1
    log_file_name="mylog"
    touch $log_file_name.log
    Maxlines=15

    lines_cnt=`wc -l $log_file_name.log|awk '{print $1}'`
    if [ $lines_cnt -gt $Maxlines ];then
        renamelogs
        mv $log_file_name.log ${log_file_name}_1.log
        touch $log_file_name.log
    fi
    echo logline >> $log_file_name.log
}

rm -rf mylog*


allow(){
    rm -rf Allow
   # mkdir Allow
   # cd Allow
   #echo *.txt* *.mp3*>allow.conf
   # echo *.jpg*>>allow.conf
   # cd ..
    mkdir  Allow
    read -p "Enter masks of include files : " -a arr
    for i in ${arr[@]}
    do
    echo -n "$i ">>Allow/allow.conf
    done

    echo "" >>Allow/allow.conf

    read -p "Enter masks of exclude files: " -a arr
    for i in ${arr[@]}
    do
    echo -n "$i ">>Allow/allow.conf
    done

    echo "" >>Allow/allow.conf
}

createFiles() # $1 - working dir
{
    same_data_files=(file.txt)
   d_data_files=(file.jpg file.mp3)

    log "I was called as :"
    pushd $1 1>/dev/null #cd $1
    log we are in `pwd`
    content=""
    if [[ $1 = *"HomeComp" ]]; then
        _date=$_homeCompDate
    else
        _date=`date +"%Y%m%d%H%M"`
        content="text"
    fi
    c=$_count
    log $_count
    while  (( $c > 0 )); do

        for i in "${same_data_files[@]}"
        do
            _fn=$i$c
            log creating $_fn with date $_date
            echo $content>$_fn
            touch -t $_date $_fn
        done

        for i in "${d_data_files[@]}"
        do
            _fn=$i$c
            log creating $_fn with current date
            echo $content>$_fn
            touch $_fn
           # sleep 1
        done
    c=$((c - 1))
    done;
    popd 1>/dev/null #cd ..
}

mydirs=(HomeComp WorkComp);


for i in "${mydirs[@]}"
do
	log deleting $i
	rm -rf $i
done

for i in "${mydirs[@]}"
do
	log creating  $i
	mkdir $i
done

for i in "${mydirs[@]}"
do
	log create Files in  $i
    createFiles $i
done

allow

_include=`head -n 1  Allow/allow.conf`
_exclude=`tail -n 1  Allow/allow.conf`

log _include=${_include[@]}
log _exclude=${_exclude[@]}

i=0
for elem in ${_include[@]}
do
	include[$i]="--include=$elem"
	i=$(($i+1))
done

i=0

for elem in ${_exclude[@]}
do
	exclude[$i]="--exclude=$elem"
	i=$(($i+1))
done

log include=${include[@]}
log exclude=${exclude[@]}
logLinesArr=`rsync  --log-file=/dev/stdout -a -u "${exclude[@]}" "${include[@]}"  --exclude='*' "HomeComp"/ "WorkComp"/`
for elem in ${logLinesArr[@]}
do
	log $elem
done
logLinesArr=`rsync  --log-file=/dev/stdout -a -u "${exclude[@]}" "${include[@]}"  --exclude='*' "WorkComp"/ "HomeComp"/`
for elem in ${logLinesArr[@]}
do
	log $elem
done

